# Generated by Django 4.0.5 on 2022-06-15 11:26

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='nophoto.png', storage=djongo.storage.GridFSStorage(base_url='/media/product_images/', collection='product_images'), upload_to='products/'),
        ),
    ]
