# Generated by Django 4.0.5 on 2022-06-03 09:08

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('public_key', models.CharField(max_length=50)),
                ('private_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.CharField(max_length=50)),
                ('e_id', models.CharField(max_length=50)),
                ('cart', models.JSONField(verbose_name=employee.models.Products)),
                ('price', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('p_name', models.CharField(max_length=50)),
                ('package_size', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('dimensions', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
            ],
        ),
    ]
